/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hyungjung Kim (https://sketchfab.com/hyungjungkim)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cloud-81910476b24d4fc5a73c908d6c2a38a2
Title: Low Poly Cloud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap'
import { useGSAP } from '@gsap/react'

const Cloud = ({ animationProps, ...props }) => {
  const ref = useRef();
  const { nodes, materials } = useGLTF('./models/cloud.glb')
  useGSAP(() => {
    // Create a timeline for smooth, continuous animation
    gsap.to(ref.current.position, animationProps);
  }, [ref]);
  
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={props.rotation || [-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload('./models/cloud.glb')

export default Cloud;
